name: PSScriptAnalyzer
on: 
  push:
    branches:
      - main
    paths:
      - '**.ps1'
      - '!tests/**'
  pull_request:
      branches:
        - main
      paths:
      - '**.ps1'
      - '!tests/**'
  
  workflow_dispatch:
  
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        sendComment: true
        failOnWarnings: false
        failOnInfos: false
