# This is a basic workflow to help you get started with Actions

name: EVTX Analysis Tool

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get SuperCAT Repo
      - uses: actions/checkout@v2.3.5

      # Get the EVTX repo and collect all the EVTX files in the repo into a single folder (I do not know how to do this)
      - name: Get EVTX repo
      # - uses: sbousseaden/EVTX-ATTACK-SAMPLES@latest

      # Check that we got all the files we expected
      - name: List Files
        shell: pwsh
        run: Get-ChildItem -Recurse
        
      # Use the Template EventIDs file to analyze the EVTX files and filter
      
      # Check results
